### ISSUE TITLE
How to actually use the Python script ? "cannot import name 'Palette' from 'PIL.Image' "

### ISSUE THREAD

**Issue by Lantern47** [Elefant-Freeciv/Civ3Full#1]
Hello, I've tried to use the script but it ran into the following error:

> Traceback (most recent call last):
File "/home/byron/Vidya/PC/Linux/Freeciv_Tools/Civ 3 Full V2.0/Civ3Tileset.py", line 6, in <module>
    from PIL.Image import Palette
ImportError: cannot import name 'Palette' from 'PIL.Image' (/usr/lib/python3.9/site-packages/PIL/Image.py)

I've gone through the various README's but I can't find any instructions regarding where certain files should be in order for the script to work. Any help would be greatly appreciated.

**Comment by Elefant-Freeciv** [comment]
Did you install pillow or PIL? PIL is outdated, and will not work. Try pip install pillow, python3 -m pip install pillow, or sudo apt-get install python3-pillow.

**Comment by Lantern47** [comment]
Apparently I already had pillow installed:

> Requirement already satisfied: pillow in /usr/lib/python3.9/site-packages (8.4.0)

**Comment by Elefant-Freeciv** [comment]
8.4.0 is very old and may not support pallette operations. You could try pip install pillow --upgrade to get a newer version

**Comment by Elefant-Freeciv** [comment]
The script needs at least pillow 9.3.0, due to some bug fixes included in that release. The readme has been updated to reflect this.

**Comment by Elefant-Freeciv** [comment]
Made some changes to the script. It should work on Linux now.
